## Import Libraries

In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras import optimizers, losses

## Data

In [2]:
sentences = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [3]:
sentences

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

## Define the Vocabulary Size

In [4]:
vocabulary_size = 10000

In [5]:
one_hot_representation = [one_hot(words, vocabulary_size) for words in sentences]
one_hot_representation

[[2426, 5314, 7451, 8618],
 [2426, 5314, 7451, 9553],
 [2426, 721, 7451, 5881],
 [2856, 6763, 7062, 8722],
 [2856, 6763, 7062, 8223, 8371],
 [7157, 2426, 7454, 7451, 7796],
 [8201, 9199, 6996, 8223]]

## Word Embedding Representation

In [6]:
sentence_length = 8

In [7]:
embedded_documents = pad_sequences(
    one_hot_representation,
    padding='pre',
    # padding='post',
    maxlen=sentence_length
)

embedded_documents

array([[   0,    0,    0,    0, 2426, 5314, 7451, 8618],
       [   0,    0,    0,    0, 2426, 5314, 7451, 9553],
       [   0,    0,    0,    0, 2426,  721, 7451, 5881],
       [   0,    0,    0,    0, 2856, 6763, 7062, 8722],
       [   0,    0,    0, 2856, 6763, 7062, 8223, 8371],
       [   0,    0,    0, 7157, 2426, 7454, 7451, 7796],
       [   0,    0,    0,    0, 8201, 9199, 6996, 8223]], dtype=int32)

## Feature Representation and Model Training

In [8]:
dimensions = 10

In [9]:
optimizer = optimizers.Adam(learning_rate=0.001)
loss = losses.MeanSquaredError()

In [10]:
model = Sequential()

model.add(Embedding(input_dim=vocabulary_size, output_dim=dimensions, input_shape=(sentence_length,)))

model.compile(
    optimizer=optimizer,
    loss=loss
)

C:\Users\SAAD TARIQ\anaconda3\envs\imdb-env\Lib\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_documents)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


array([[[-1.75543875e-03,  1.26528181e-02,  1.49770863e-02,
         -2.91668251e-03,  3.19377333e-03, -3.19164544e-02,
          1.07761733e-02,  3.38412449e-03, -3.44589353e-06,
          4.85327579e-02],
        [-1.75543875e-03,  1.26528181e-02,  1.49770863e-02,
         -2.91668251e-03,  3.19377333e-03, -3.19164544e-02,
          1.07761733e-02,  3.38412449e-03, -3.44589353e-06,
          4.85327579e-02],
        [-1.75543875e-03,  1.26528181e-02,  1.49770863e-02,
         -2.91668251e-03,  3.19377333e-03, -3.19164544e-02,
          1.07761733e-02,  3.38412449e-03, -3.44589353e-06,
          4.85327579e-02],
        [-1.75543875e-03,  1.26528181e-02,  1.49770863e-02,
         -2.91668251e-03,  3.19377333e-03, -3.19164544e-02,
          1.07761733e-02,  3.38412449e-03, -3.44589353e-06,
          4.85327579e-02],
        [-2.03192364e-02,  3.17842476e-02,  4.88684438e-02,
          1.53386258e-02, -3.19895521e-02, -4.90811579e-02,
         -2.62093544e-03,  4.41084392e-02, -2.007849

In [13]:
embedded_documents[0]

array([   0,    0,    0,    0, 2426, 5314, 7451, 8618], dtype=int32)

In [15]:
input_example = np.expand_dims(embedded_documents[0], axis=0)
model.predict(input_example)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


array([[[-1.7554387e-03,  1.2652818e-02,  1.4977086e-02, -2.9166825e-03,
          3.1937733e-03, -3.1916454e-02,  1.0776173e-02,  3.3841245e-03,
         -3.4458935e-06,  4.8532758e-02],
        [-1.7554387e-03,  1.2652818e-02,  1.4977086e-02, -2.9166825e-03,
          3.1937733e-03, -3.1916454e-02,  1.0776173e-02,  3.3841245e-03,
         -3.4458935e-06,  4.8532758e-02],
        [-1.7554387e-03,  1.2652818e-02,  1.4977086e-02, -2.9166825e-03,
          3.1937733e-03, -3.1916454e-02,  1.0776173e-02,  3.3841245e-03,
         -3.4458935e-06,  4.8532758e-02],
        [-1.7554387e-03,  1.2652818e-02,  1.4977086e-02, -2.9166825e-03,
          3.1937733e-03, -3.1916454e-02,  1.0776173e-02,  3.3841245e-03,
         -3.4458935e-06,  4.8532758e-02],
        [-2.0319236e-02,  3.1784248e-02,  4.8868444e-02,  1.5338626e-02,
         -3.1989552e-02, -4.9081158e-02, -2.6209354e-03,  4.4108439e-02,
         -2.0078493e-02,  1.2762155e-02],
        [ 4.8874501e-02, -4.7078561e-02,  2.0931732e-02,  3.