## Import Libraries

In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras import optimizers, losses

import warnings
warnings.filterwarnings('ignore')

## Data

In [2]:
sentences = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [3]:
sentences

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

## Define the Vocabulary Size

In [4]:
vocabulary_size = 10000

In [5]:
one_hot_representation = [one_hot(words, vocabulary_size) for words in sentences]
one_hot_representation

[[73, 1816, 6056, 2306],
 [73, 1816, 6056, 2474],
 [73, 7999, 6056, 6642],
 [8909, 7556, 9977, 4276],
 [8909, 7556, 9977, 9306, 3984],
 [5663, 73, 5418, 6056, 9333],
 [8226, 9829, 314, 9306]]

## Word Embedding Representation

In [6]:
sentence_length = 8

In [7]:
embedded_documents = pad_sequences(
    one_hot_representation,
    padding='pre',
    # padding='post',
    maxlen=sentence_length
)

embedded_documents

array([[   0,    0,    0,    0,   73, 1816, 6056, 2306],
       [   0,    0,    0,    0,   73, 1816, 6056, 2474],
       [   0,    0,    0,    0,   73, 7999, 6056, 6642],
       [   0,    0,    0,    0, 8909, 7556, 9977, 4276],
       [   0,    0,    0, 8909, 7556, 9977, 9306, 3984],
       [   0,    0,    0, 5663,   73, 5418, 6056, 9333],
       [   0,    0,    0,    0, 8226, 9829,  314, 9306]], dtype=int32)

## Feature Representation and Model Training

In [8]:
dimensions = 10

In [9]:
optimizer = optimizers.Adam(learning_rate=0.001)
loss = losses.MeanSquaredError()

In [10]:
model = Sequential()

model.add(Embedding(input_dim=vocabulary_size, output_dim=dimensions, input_shape=(sentence_length,)))

model.compile(
    optimizer=optimizer,
    loss=loss
)

In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_documents)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


array([[[-0.00596559,  0.03054111,  0.04689955, -0.00282722,
          0.03639487, -0.0014166 , -0.00207208,  0.00443318,
          0.04220575,  0.04393994],
        [-0.00596559,  0.03054111,  0.04689955, -0.00282722,
          0.03639487, -0.0014166 , -0.00207208,  0.00443318,
          0.04220575,  0.04393994],
        [-0.00596559,  0.03054111,  0.04689955, -0.00282722,
          0.03639487, -0.0014166 , -0.00207208,  0.00443318,
          0.04220575,  0.04393994],
        [-0.00596559,  0.03054111,  0.04689955, -0.00282722,
          0.03639487, -0.0014166 , -0.00207208,  0.00443318,
          0.04220575,  0.04393994],
        [ 0.02905089, -0.03191014, -0.04711958, -0.03315663,
          0.00977664, -0.01757487, -0.01024494, -0.04969617,
          0.01395838,  0.04868854],
        [ 0.01384025, -0.01481377,  0.03252225, -0.02803394,
          0.00848915, -0.04511019, -0.01351049, -0.02306713,
         -0.00836868, -0.00919125],
        [ 0.03305507, -0.0441818 , -0.01678448, -0.0

In [13]:
embedded_documents[0]

array([   0,    0,    0,    0,   73, 1816, 6056, 2306], dtype=int32)

In [14]:
input_example = np.expand_dims(embedded_documents[0], axis=0)
model.predict(input_example)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[[-0.00596559,  0.03054111,  0.04689955, -0.00282722,
          0.03639487, -0.0014166 , -0.00207208,  0.00443318,
          0.04220575,  0.04393994],
        [-0.00596559,  0.03054111,  0.04689955, -0.00282722,
          0.03639487, -0.0014166 , -0.00207208,  0.00443318,
          0.04220575,  0.04393994],
        [-0.00596559,  0.03054111,  0.04689955, -0.00282722,
          0.03639487, -0.0014166 , -0.00207208,  0.00443318,
          0.04220575,  0.04393994],
        [-0.00596559,  0.03054111,  0.04689955, -0.00282722,
          0.03639487, -0.0014166 , -0.00207208,  0.00443318,
          0.04220575,  0.04393994],
        [ 0.02905089, -0.03191014, -0.04711958, -0.03315663,
          0.00977664, -0.01757487, -0.01024494, -0.04969617,
          0.01395838,  0.04868854],
        [ 0.01384025, -0.01481377,  0.03252225, -0.02803394,
          0.00848915, -0.04511019, -0.01351049, -0.02306713,
         -0.00836868, -0.00919125],
        [ 0.03305507, -0.0441818 , -0.01678448, -0.0